# Site settings
title: Sanimap
mobile_title: Sanimap
description: Mapa del Sistema Sanitari de Catalunya.
baseurl: ""
url: https://example.com
email: your-email@domain.com
lang: ca
google_analytics: UA-XXXXX-X

# Where things are
source: src
destination: app

# Collections
collections:
  - home

# Handling Reading
encoding: "utf-8"
markdown_ext: "md"

# Plugins
# gems:
#   - jekyll-feed

# Conversion
markdown: kramdown
highlighter: rouge

# Outputting
permalink: pretty
timezone: Europe/Madrid
