# Site settings
title: Mapa del Sistema Sanitari de Catalunya
mobile_title: Sanimap
description: Mapeig de la situació de la sanitat catalana i de les campanyes ciutadanes per defensar-la.
author: "Confederació d’Associacions Veïnals de Catalunya (CONFAVC)"
baseurl: ""
url: https://sanimap.confavc.cat
email: veins@confavc.cat
lang: ca
google_analytics: UA-XXXXX-X
logo: sanimap-logo-64x35.png

# Where things are
source: src
destination: app
images_path: images
scripts_path: scripts
styles_path: styles

# Collections
collections:
  casos:
    output: true
    permalink: /:collection/:title.html
  casos-d-estudi:
    output: false
  home:
    output: false
  patrocinadors:
    output: false

defaults:
  - scope:
      path: ""
      type: "casos"
    values:
      layout: "cas"

# Handling Reading
encoding: "utf-8"
markdown_ext: "md"

# Plugins
# gems:
#   - jekyll-feed

# Conversion
markdown: kramdown
highlighter: rouge

# Outputting
permalink: pretty
timezone: Europe/Madrid
